import { writeFileSync } from 'fs';

import { transform } from './transform';

// Mock out FS to avoid writing to disk
// We aren't processing the result anyway, so no need for specifying the response
jest.mock('fs');

// Pre-transformed code as emitted by @compiled/vanilla globalStylesheet handler
const injectGlobalStylesCode = `
  import { injectGlobalStyles } from '@compiled/vanilla/runtime';
  export const styles = { tableCell: 'gs_abc1234' };
  injectGlobalStyles('.gs_abc1234 .pm-table-cell{padding:8px}', 'gs_abc1234');
`;

describe('babel-plugin-strip-runtime with stylesheet extraction (extractStylesToDirectory)', () => {
  describe('with the classic runtime', () => {
    const runtime = 'classic';

    describe('without JSX pragma', () => {
      const code = `
        import '@compiled/react';

        const Component = () => (
          <div css={{ fontSize: 12, color: 'blue' }}>
            hello world
          </div>
        );
      `;

      it('adds styles to directory', () => {
        const actual = transform(code, {
          run: 'both',
          runtime,
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import * as React from 'react';
          import { ax, ix } from '@compiled/react/runtime';
          const Component = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz13q2']),
              },
              'hello world'
            );
          "
        `);

        expect(writeFileSync).toBeCalledWith(
          expect.stringContaining('app.compiled.css'),
          '._1wyb1fwx{font-size:12px}\n._syaz13q2{color:blue}'
        );
      });

      it('error when source directory is not found', () => {
        expect(() =>
          transform(code, {
            run: 'both',
            runtime,
            extractStylesToDirectory: { source: 'not-existing-src/', dest: 'dist/' },
          })
        ).toThrowWithMessage(
          Error,
          `/base/src/app.tsx: Source directory 'not-existing-src/' was not found relative to source file ('../src/app.tsx')`
        );
      });
    });

    describe('with JSX pragma', () => {
      it('extracts styles into app.compiled.css', () => {
        const codeWithPragma = `
          /** @jsx myJsx */
          import { css, jsx as myJsx } from '@compiled/react';

          const Component = () => (
            <div css={{ fontSize: 12, color: 'blue' }}>
              hello world 2
            </div>
          );

          const Component2 = () => (
            <div css={css({ fontSize: 12, color: 'pink' })}>
              hello world 2
            </div>
          );
        `;

        const actual = transform(codeWithPragma, {
          run: 'both',
          runtime: 'classic',
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import * as React from 'react';
          import { ax, ix } from '@compiled/react/runtime';
          const Component = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz13q2']),
              },
              'hello world 2'
            );
          const Component2 = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz32ev']),
              },
              'hello world 2'
            );
          "
        `);
      });
    });
  });

  describe('with the automatic runtime', () => {
    describe('with JSX pragma', () => {
      it('extracts styles into app.compiled.css', () => {
        const codeWithPragma = `
          /** @jsxImportSource @compiled/react */
          import { css } from '@compiled/react';

          const Component = () => (
            <div css={{ fontSize: 12, color: 'blue' }}>
              hello world 2
            </div>
          );

          const Component2 = () => (
            <div css={css({ fontSize: 12, color: 'pink' })}>
              hello world 2
            </div>
          );
        `;

        const actual = transform(codeWithPragma, {
          run: 'both',
          runtime: 'automatic',
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import { ax, ix } from '@compiled/react/runtime';
          import { jsxs as _jsxs, jsx as _jsx } from 'react/jsx-runtime';
          const Component = () =>
            /*#__PURE__*/ _jsx('div', {
              className: ax(['_1wyb1fwx _syaz13q2']),
              children: 'hello world 2',
            });
          const Component2 = () =>
            /*#__PURE__*/ _jsx('div', {
              className: ax(['_1wyb1fwx _syaz32ev']),
              children: 'hello world 2',
            });
          "
        `);
      });
    });
  });
});

describe('babel-plugin-strip-runtime handling injectGlobalStyles()', () => {
  const runtime = 'classic';

  it('removes the injectGlobalStyles() call from output', () => {
    const actual = transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
      extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
    });

    expect(actual).not.toContain('injectGlobalStyles');
  });

  it('removes the import { injectGlobalStyles } from @compiled/vanilla/runtime', () => {
    const actual = transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
      extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
    });

    expect(actual).not.toContain('@compiled/vanilla/runtime');
  });

  it('adds a .global.css import to the file', () => {
    const actual = transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
      extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
    });

    expect(actual).toContain("import './app.global.css'");
  });

  it('preserves non-stripped exports', () => {
    const actual = transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
      extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
    });

    expect(actual).toContain("tableCell: 'gs_abc1234'");
  });

  it('writes the CSS content to app.global.css', () => {
    transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
      extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
    });

    expect(writeFileSync).toBeCalledWith(
      expect.stringContaining('app.global.css'),
      '.gs_abc1234 .pm-table-cell{padding:8px}'
    );
  });

  it('works without extractStylesToDirectory (writes alongside source file)', () => {
    const actual = transform(injectGlobalStylesCode, {
      run: 'extract',
      runtime,
    });

    expect(actual).not.toContain('injectGlobalStyles');
    expect(actual).not.toContain('@compiled/vanilla/runtime');
    expect(actual).toContain("import './app.global.css'");

    expect(writeFileSync).toBeCalledWith(
      expect.stringContaining('app.global.css'),
      '.gs_abc1234 .pm-table-cell{padding:8px}'
    );
  });
});
